// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * The broad accounting class of a ledger account.
 */
export type AccountClass = "Asset" | "Liability" | "Equity" | "Income" | "Expense";
