// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * The specific subtype of a ledger account.
 */
export type AccountType = "Cash" | "Savings" | "Checking" | "CreditCard" | "Loan" | "Investment" | "LoyaltyPoints" | "Prepayment";
