// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { PermissionLevel } from "./PermissionLevel";

export type AccountPermissionDto = { account_id: string, user_id: string, level: PermissionLevel, granted_by: string | null, created_at: string, };
