// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { AccountClass } from "./AccountClass";
import type { AccountType } from "./AccountType";
import type { OwnershipType } from "./OwnershipType";

/**
 * Data Transfer Object representing a ledger account.
 */
export type AccountDto = { 
/**
 * Unique identifier of the account.
 */
id: string, 
/**
 * The user-facing name of the account.
 */
name: string, 
/**
 * Broad class of the account (e.g. Asset, Liability, Equity, Revenue, Expense).
 */
class: AccountClass, 
/**
 * Detailed account sub-type (e.g. Cash, Checking, CreditCard).
 */
type_: AccountType, 
/**
 * Three-letter ISO currency code (e.g. "USD", "EUR").
 */
currency_code: string, 
/**
 * Ownership model for the account (e.g. Individual or Group).
 */
ownership_type: OwnershipType, 
/**
 * Optional identifier of the associated bank entity.
 */
bank_id: string | null, 
/**
 * Optional identifier of the parent account, for hierarchical accounts.
 */
parent_id: string | null, 
/**
 * Optional identifier of the individual user owner (if ownership_type is Individual).
 */
user_id: string | null, 
/**
 * Optional identifier of the group owner (if ownership_type is Group).
 */
group_id: string | null, 
/**
 * True if the account is active and open.
 */
is_active: boolean, 
/**
 * The timestamp when the account record was last updated on the client.
 */
client_updated_at: string, 
/**
 * Version number of the account record.
 */
version: number, 
/**
 * The timestamp when the account was created.
 */
created_at: string, };
