// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { AccountClass } from "./AccountClass";
import type { AccountType } from "./AccountType";
import type { OwnershipType } from "./OwnershipType";

export type AccountDto = { id: string, name: string, class: AccountClass, type_: AccountType, currency_code: string, ownership_type: OwnershipType, bank_id: string | null, parent_id: string | null, user_id: string | null, group_id: string | null, is_active: boolean, client_updated_at: string, version: number, created_at: string, };
