// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { PermissionLevel } from "./PermissionLevel";

/**
 * Data Transfer Object representing user permissions on a specific account.
 */
export type AccountPermissionDto = { 
/**
 * Unique identifier of the target account.
 */
account_id: string, 
/**
 * Unique identifier of the user who has permissions.
 */
user_id: string, 
/**
 * Permission level granted (Read, Write, Admin).
 */
level: PermissionLevel, 
/**
 * Optional identifier of the administrator user who granted this permission.
 */
granted_by: string | null, 
/**
 * The timestamp when this permission was granted.
 */
created_at: string, };
