// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Data Transfer Object representing a financial institution/bank.
 */
export type BankDto = { 
/**
 * Unique identifier of the bank.
 */
id: string, 
/**
 * The name of the bank (e.g. "Chase", "HSBC").
 */
name: string, 
/**
 * Two-letter ISO country code where the bank is located.
 */
country_code: string, 
/**
 * The timestamp when this bank record was created.
 */
created_at: string, };
