// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type BankDto = { id: string, name: string, country_code: string, created_at: string, };
