// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * The transaction types supported by a card.
 */
export type CardTransactionType = "Purchase" | "Withdrawal" | "All";
