// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Carryover resolution method.
 */
export type CarryoverResolutionMethod = "DeductInFull" | "Amortize" | "SavingsOffset";
