// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Carryover resolution status.
 */
export type CarryoverResolutionStatus = "Pending" | "Applied" | "Dismissed";
