// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Compounding frequency for loans or investments.
 */
export type CompoundingFreq = "Daily" | "Monthly" | "Annually";
