// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * DTO for creating a new user session.
 */
export type CreateSessionDto = { 
/**
 * Unique identifier for the new session.
 */
id: string, 
/**
 * Unique identifier of the user who owns this session.
 */
user_id: string, 
/**
 * Optional User-Agent browser string.
 */
user_agent: string | null, 
/**
 * Optional IP address string.
 */
ip_address: string | null, 
/**
 * Expiration timestamp of the session.
 */
expires_at: string, };
