// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Data Transfer Object representing a currency rate.
 */
export type CurrencyRateDto = { 
/**
 * Unique identifier of the rate record.
 */
id: string, 
/**
 * Base currency code.
 */
from_currency: string, 
/**
 * Target currency code.
 */
to_currency: string, 
/**
 * The exchange rate scaled by 10^10.
 */
rate: bigint, 
/**
 * The date when this rate applies.
 */
rate_date: string, 
/**
 * The creation timestamp.
 */
created_at: string, };
