// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Data Transfer Object representing a currency configuration.
 */
export type CurrencyDto = { 
/**
 * Three-letter ISO currency code (e.g. "USD", "EUR").
 */
code: string, 
/**
 * Human-readable name of the currency (e.g. "US Dollar").
 */
name: string, 
/**
 * Currency symbol (e.g. "$", "€").
 */
symbol: string, 
/**
 * Number of decimal places used (e.g. 2 for USD, 0 for JPY).
 */
decimals: number, };
