// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * DTO for enabling multi-factor authentication (MFA) for a user.
 */
export type EnableMfaDto = { 
/**
 * Unique identifier of the user to enable MFA for.
 */
user_id: string, 
/**
 * The TOTP shared secret key.
 */
secret: string, };
