// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Friendship status between two users.
 */
export type FriendshipStatus = "Pending" | "Accepted" | "Blocked";
