// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { FriendshipStatus } from "./FriendshipStatus";

/**
 * Data Transfer Object representing a friendship relation.
 */
export type FriendshipDto = { 
/**
 * Unique identifier of the first user.
 */
user_id1: string, 
/**
 * Unique identifier of the second user.
 */
user_id2: string, 
/**
 * The current status of the friendship.
 */
status: FriendshipStatus, 
/**
 * Identifier of the user who initiated the request.
 */
initiated_by: string, 
/**
 * Creation timestamp.
 */
created_at: string, };
