// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { PermissionLevel } from "./PermissionLevel";

/**
 * DTO for granting or updating permissions on an account.
 */
export type GrantPermissionDto = { 
/**
 * Unique identifier of the administrator user who is granting the permission.
 */
admin_user_id: string, 
/**
 * Unique identifier of the target user receiving permissions.
 */
target_user_id: string, 
/**
 * Unique identifier of the target account.
 */
account_id: string, 
/**
 * The permission level to grant.
 */
level: PermissionLevel, };
