// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Data Transfer Object representing a user group.
 */
export type GroupDto = { 
/**
 * Unique identifier of the group.
 */
id: string, 
/**
 * Name of the group.
 */
name: string, 
/**
 * The timestamp when the group was updated on the client side.
 */
client_updated_at: string, 
/**
 * Version number of the group record for optimistic locking.
 */
version: number, 
/**
 * The timestamp when the group was created.
 */
created_at: string, };
