// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Data Transfer Object representing a group membership link.
 */
export type GroupMemberDto = { 
/**
 * Unique identifier of the group.
 */
group_id: string, 
/**
 * Unique identifier of the user who is a member.
 */
user_id: string, 
/**
 * The role of the user within the group (e.g. "Owner", "Admin", "Member").
 */
role: string, 
/**
 * The timestamp when the user joined the group.
 */
joined_at: string, };
