// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type GroupDto = { id: string, name: string, client_updated_at: string, version: number, created_at: string, };
