// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Data Transfer Object representing an insurance policy.
 */
export type InsurancePolicyDto = { 
/**
 * Unique identifier of the policy.
 */
id: string, 
/**
 * Name.
 */
name: string, 
/**
 * Policy number.
 */
policy_number: string | null, 
/**
 * Insurance provider.
 */
provider: string, 
/**
 * Deductible amount scaled by 10^4.
 */
deductible: bigint, 
/**
 * Optional coverage limit scaled by 10^4.
 */
coverage_limit: bigint | null, 
/**
 * Currency code.
 */
currency_code: string, 
/**
 * Premium amount scaled by 10^4.
 */
premium_amount: bigint, 
/**
 * Optional recurring schedule ID associated with premiums.
 */
premium_schedule_id: string | null, 
/**
 * Optional owner user ID.
 */
user_id: string | null, 
/**
 * Optional owner group ID.
 */
group_id: string | null, 
/**
 * Last updated timestamp.
 */
client_updated_at: string, 
/**
 * Version.
 */
version: number, 
/**
 * Creation timestamp.
 */
created_at: string, };
