// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ClaimStatus } from "./ClaimStatus";

/**
 * Data Transfer Object representing an insurance claim.
 */
export type InsuranceClaimDto = { 
/**
 * Unique identifier of the claim.
 */
id: string, 
/**
 * Associated policy ID.
 */
policy_id: string, 
/**
 * Title of the claim.
 */
title: string, 
/**
 * Date of incident.
 */
incident_date: string, 
/**
 * Claim status.
 */
status: ClaimStatus, 
/**
 * Total cost of incident scaled by 10^4.
 */
total_cost: bigint, 
/**
 * Deductible paid scaled by 10^4.
 */
deductible_paid: bigint, 
/**
 * Expected reimbursement scaled by 10^4.
 */
expected_reimbursement: bigint, 
/**
 * Actual payout received scaled by 10^4.
 */
actual_payout: bigint, 
/**
 * Optional ledger transaction ID for the incident costs.
 */
transaction_id: string | null, 
/**
 * Optional ledger transaction ID for the claim payout.
 */
payout_transaction_id: string | null, 
/**
 * Receivable account ID (Asset).
 */
receivable_account_id: string, 
/**
 * Expense account ID (Expense).
 */
expense_account_id: string, 
/**
 * Last updated timestamp.
 */
client_updated_at: string, 
/**
 * Version.
 */
version: number, 
/**
 * Creation timestamp.
 */
created_at: string, };
