// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { SplitMethod } from "./SplitMethod";

/**
 * Data Transfer Object representing an item split.
 */
export type ItemSplitDto = { 
/**
 * Unique identifier.
 */
id: string, 
/**
 * Optional identifier of the associated receipt item.
 */
receipt_item_id: string | null, 
/**
 * Optional identifier of the associated receipt header.
 */
receipt_header_id: string | null, 
/**
 * Identifier of the user this split applies to.
 */
user_id: string, 
/**
 * Split method used.
 */
method: SplitMethod, 
/**
 * Split value (scaled by 10^4).
 */
value: bigint, 
/**
 * Resolved currency amount (scaled by 10^4).
 */
resolved_amount: bigint, 
/**
 * True if this split is a gift.
 */
is_gift: boolean, 
/**
 * Optional identifier of the user who paid for/gifted this split.
 */
gifter_user_id: string | null, 
/**
 * True if the split is disputed by the user.
 */
is_disputed: boolean, 
/**
 * Last updated timestamp.
 */
client_updated_at: string, 
/**
 * Version number.
 */
version: number, };
