// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Data Transfer Object representing a single journal entry (debit or credit leg) of a transaction.
 */
export type JournalEntryDto = { 
/**
 * Unique identifier of the journal entry.
 */
id: string, 
/**
 * Identifier of the parent transaction this entry belongs to.
 */
transaction_id: string, 
/**
 * Identifier of the account affected by this entry.
 */
account_id: string, 
/**
 * Optional identifier of the debit card used, if any.
 */
debit_card_id: string | null, 
/**
 * Optional identifier of the card fee rule applied.
 */
card_fee_rule_id: string | null, 
/**
 * The entry amount. Positive for debits, negative for credits, scaled by 10^4.
 */
amount: bigint, 
/**
 * Currency code of the entry.
 */
currency_code: string, 
/**
 * Exchange rate relative to the base currency, scaled by 10^6.
 */
exchange_rate: bigint, 
/**
 * Optional memo or note for this specific entry.
 */
memo: string | null, };
