// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type JournalEntryDto = { id: string, transaction_id: string, account_id: string, debit_card_id: string | null, card_fee_rule_id: string | null, amount: bigint, currency_code: string, exchange_rate: bigint, memo: string | null, };
