// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Kakebo budget category classification.
 */
export type KakeboCategory = "Needs" | "Wants" | "Culture" | "Unexpected";
