// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type LocationDto = { id: string, merchant_id: string, name: string, street: string | null, neighborhood: string | null, city: string | null, state: string | null, zip_code: string | null, latitude: string | null, longitude: string | null, created_at: string, };
