// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Data Transfer Object representing a specific merchant location or branch.
 */
export type LocationDto = { 
/**
 * Unique identifier of the location.
 */
id: string, 
/**
 * Unique identifier of the merchant who owns this location.
 */
merchant_id: string, 
/**
 * Human-readable name of the branch/location (e.g. "Downtown Branch").
 */
name: string, 
/**
 * Street name and number.
 */
street: string | null, 
/**
 * Neighborhood name.
 */
neighborhood: string | null, 
/**
 * City name.
 */
city: string | null, 
/**
 * State or province name.
 */
state: string | null, 
/**
 * Postal/ZIP code.
 */
zip_code: string | null, 
/**
 * Latitude coordinate for GPS mapping.
 */
latitude: string | null, 
/**
 * Longitude coordinate for GPS mapping.
 */
longitude: string | null, 
/**
 * The timestamp when this location was recorded.
 */
created_at: string, };
