// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Measurement unit for receipt items.
 */
export type MeasurementUnit = "Piece" | "Gram" | "Kilogram" | "Ounce" | "Pound" | "Milliliter" | "Liter" | "FluidOunce" | "Gallon" | "Meter" | "Centimeter";
