// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Data Transfer Object representing a merchant (business or vendor).
 */
export type MerchantDto = { 
/**
 * Unique identifier of the merchant.
 */
id: string, 
/**
 * Optional parent merchant ID (e.g. for parent corporate entities or franchises).
 */
parent_id: string | null, 
/**
 * The name of the merchant (e.g. "Walmart").
 */
name: string, 
/**
 * Optional country code where the merchant is registered.
 */
country_code: string | null, 
/**
 * Optional default currency code associated with the merchant.
 */
default_currency_code: string | null, 
/**
 * The timestamp when the merchant was created.
 */
created_at: string, };
