// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type MerchantDto = { id: string, parent_id: string | null, name: string, country_code: string | null, default_currency_code: string | null, created_at: string, };
