// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Data Transfer Object representing a monthly budget setup.
 */
export type MonthlyBudgetDto = { 
/**
 * Unique identifier.
 */
id: string, 
/**
 * Optional owner user ID.
 */
user_id: string | null, 
/**
 * Optional owner group ID.
 */
group_id: string | null, 
/**
 * Budget year.
 */
year: number, 
/**
 * Budget month.
 */
month: number, 
/**
 * Target income scaled by 10^4.
 */
income_budget: bigint, 
/**
 * Savings target in basis points.
 */
savings_target_bps: number, 
/**
 * Last updated timestamp.
 */
client_updated_at: string, 
/**
 * Version.
 */
version: number, 
/**
 * Creation timestamp.
 */
created_at: string, };
