// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Overpayment preference for debt resolution.
 */
export type OverpaymentPref = "SelectedLoan" | "HighestInterest" | "HighestPrincipal" | "CreateNewDebt" | "Default";
