// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * The ownership structure of a ledger account.
 */
export type OwnershipType = "Individual" | "JointOr" | "JointAnd" | "System";
