// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Data Transfer Object representing the header of a purchase receipt.
 */
export type ReceiptHeaderDto = { 
/**
 * Unique identifier of the receipt.
 */
id: string, 
/**
 * Identifier of the associated double-entry ledger transaction.
 */
transaction_id: string, 
/**
 * Identifier of the merchant location where the purchase took place.
 */
location_id: string, 
/**
 * The date of the purchase.
 */
date: string, 
/**
 * Total taxes paid on the receipt, scaled by 10^4 (or minor currency unit representation).
 */
taxes: bigint, 
/**
 * Optional tip amount paid, scaled by 10^4.
 */
tips: bigint, 
/**
 * Three-letter ISO currency code (e.g. "USD").
 */
currency_code: string, };
