// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { TaxType } from "./TaxType";

export type ReceiptItemTaxDto = { id: string, receipt_item_id: string, tax_type: TaxType, amount: bigint, rate: number | null, };
