// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { MeasurementUnit } from "./MeasurementUnit";

/**
 * Data Transfer Object representing an individual item on a receipt.
 */
export type ReceiptItemDto = { 
/**
 * Unique identifier of the receipt item.
 */
id: string, 
/**
 * Unique identifier of the receipt this item belongs to.
 */
receipt_id: string, 
/**
 * Name or description of the purchased item.
 */
name: string, 
/**
 * Quantity purchased (scaled by 10^4 to allow fractional quantities).
 */
quantity: bigint, 
/**
 * Measurement unit of the item (e.g. Piece, Gram, Liter).
 */
unit: MeasurementUnit, 
/**
 * Price per unit, scaled by 10^4.
 */
unit_price: bigint, 
/**
 * Optional identifier of the tag categorizing this item.
 */
tag_id: string | null, };
