// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { TaxType } from "./TaxType";

/**
 * Data Transfer Object representing tax details applied to a receipt as a whole.
 */
export type ReceiptTaxDto = { 
/**
 * Unique identifier of the receipt tax record.
 */
id: string, 
/**
 * Unique identifier of the receipt.
 */
receipt_id: string, 
/**
 * Type of tax applied (e.g. VAT, IEPS).
 */
tax_type: TaxType, 
/**
 * Total tax amount, scaled by 10^4.
 */
amount: bigint, 
/**
 * Tax rate percentage, scaled (e.g. 1600 for 16.00%).
 */
rate: number | null, 
/**
 * Timestamp when the tax record was created.
 */
created_at: string, };
