// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type ReceiptHeaderDto = { id: string, transaction_id: string, location_id: string, date: string, taxes: bigint, tips: bigint, currency_code: string, };
