// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { MeasurementUnit } from "./MeasurementUnit";

export type ReceiptItemDto = { id: string, receipt_id: string, name: string, quantity: bigint, unit: MeasurementUnit, unit_price: bigint, tag_id: string | null, };
