// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { TaxType } from "./TaxType";

/**
 * Data Transfer Object representing tax details applied to a specific receipt item.
 */
export type ReceiptItemTaxDto = { 
/**
 * Unique identifier of the receipt item tax record.
 */
id: string, 
/**
 * Unique identifier of the receipt item.
 */
receipt_item_id: string, 
/**
 * Type of tax applied.
 */
tax_type: TaxType, 
/**
 * Tax amount for this item, scaled by 10^4.
 */
amount: bigint, 
/**
 * Tax rate percentage.
 */
rate: number | null, };
