// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { RecurrenceFrequency } from "./RecurrenceFrequency";

/**
 * Data Transfer Object representing a recurring schedule.
 */
export type RecurringScheduleDto = { 
/**
 * Unique identifier of the recurring schedule.
 */
id: string, 
/**
 * Name.
 */
name: string, 
/**
 * Frequency of recurrence.
 */
frequency: RecurrenceFrequency, 
/**
 * Interval.
 */
interval: number, 
/**
 * Day of the month triggers.
 */
day_of_month: number | null, 
/**
 * Day of the week triggers.
 */
day_of_week: number | null, 
/**
 * Start date.
 */
start_date: string, 
/**
 * Optional end date.
 */
end_date: string | null, 
/**
 * Optional last trigger date.
 */
last_trigger_date: string | null, 
/**
 * Autopay flag.
 */
is_autopay: boolean, 
/**
 * Active flag.
 */
is_active: boolean, 
/**
 * Optional owner user ID.
 */
user_id: string | null, 
/**
 * Optional owner group ID.
 */
group_id: string | null, 
/**
 * Last updated timestamp.
 */
client_updated_at: string, 
/**
 * Version.
 */
version: number, 
/**
 * Creation timestamp.
 */
created_at: string, };
