// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Recurrence frequency for scheduled transactions.
 */
export type RecurrenceFrequency = "Daily" | "Weekly" | "Biweekly" | "Monthly" | "Quarterly" | "Annually";
