// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * DTO for revoking permissions on an account.
 */
export type RevokePermissionDto = { 
/**
 * Unique identifier of the administrator user who is revoking the permission.
 */
admin_user_id: string, 
/**
 * Unique identifier of the target user whose permissions are being revoked.
 */
target_user_id: string, 
/**
 * Unique identifier of the target account.
 */
account_id: string, };
