// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Data Transfer Object representing a savings goal.
 */
export type SavingsGoalDto = { 
/**
 * Unique identifier of the savings goal.
 */
id: string, 
/**
 * Name.
 */
name: string, 
/**
 * Target amount scaled by 10^4.
 */
target_amount: bigint, 
/**
 * Currency code.
 */
currency_code: string, 
/**
 * Optional deadline.
 */
deadline: string | null, 
/**
 * Optional owner user ID.
 */
user_id: string | null, 
/**
 * Optional owner group ID.
 */
group_id: string | null, 
/**
 * Last updated timestamp.
 */
client_updated_at: string, 
/**
 * Version.
 */
version: number, 
/**
 * Creation timestamp.
 */
created_at: string, };
