// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Method used to split expenses among group members.
 */
export type SplitMethod = "Exact" | "Percentage" | "Share" | "FullGift" | "PartialGift";
