// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { KakeboCategory } from "./KakeboCategory";

export type TagDto = { id: string, name: string, parent_id: string | null, is_fixed: boolean, kakebo_category: KakeboCategory, client_updated_at: string, version: number, };
