// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { KakeboCategory } from "./KakeboCategory";

/**
 * Data Transfer Object representing a category/classification tag.
 */
export type TagDto = { 
/**
 * Unique identifier of the tag.
 */
id: string, 
/**
 * The name of the tag (e.g. "Groceries", "Rent").
 */
name: string, 
/**
 * Optional parent tag ID, for nested categorization/hierarchies.
 */
parent_id: string | null, 
/**
 * True if this represents a fixed/unavoidable expense (otherwise variable).
 */
is_fixed: boolean, 
/**
 * Kakebo system category categorization (e.g. Survival, Leisure, Culture, Extra).
 */
kakebo_category: KakeboCategory, 
/**
 * The timestamp when the tag was last updated on the client.
 */
client_updated_at: string, 
/**
 * Version number of the tag record.
 */
version: number, };
