// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Type of tax applied to items or receipts.
 */
export type TaxType = "Vat" | "Ieps" | "IsrWithholding" | "VatWithholding" | "SalesTax" | "Other";
