// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { TransactionStatus } from "./TransactionStatus";

export type TransactionDto = { id: string, date: string, description: string | null, status: TransactionStatus, parent_transaction_id: string | null, group_id: string | null, created_by: string, base_currency_code: string, client_updated_at: string, version: number, created_at: string, };
