// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { TransactionStatus } from "./TransactionStatus";

/**
 * Data Transfer Object representing a ledger transaction header.
 */
export type TransactionDto = { 
/**
 * Unique identifier of the transaction.
 */
id: string, 
/**
 * The date the transaction occurred.
 */
date: string, 
/**
 * An optional user-supplied description.
 */
description: string | null, 
/**
 * Status of the transaction (e.g. Cleared, Pending).
 */
status: TransactionStatus, 
/**
 * Optional parent transaction ID, for split/child transactions.
 */
parent_transaction_id: string | null, 
/**
 * Optional group identifier if the transaction belongs to a group.
 */
group_id: string | null, 
/**
 * The identifier of the user who created this transaction.
 */
created_by: string, 
/**
 * Base currency code for the transaction.
 */
base_currency_code: string, 
/**
 * The timestamp when the transaction was last updated on the client.
 */
client_updated_at: string, 
/**
 * Version number of the transaction record.
 */
version: number, 
/**
 * The timestamp when the transaction was created.
 */
created_at: string, };
