// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Data Transfer Object representing a user profile and credentials state.
 */
export type UserDto = { 
/**
 * Unique identifier of the user.
 */
id: string, 
/**
 * Email address of the user, if provided.
 */
email: string | null, 
/**
 * Unique username of the user.
 */
username: string, 
/**
 * Hashed password of the user. None if they login with OAuth or are a shadow user.
 */
password_hash: string | null, 
/**
 * True if this is a "shadow" user account created on behalf of someone else (e.g. for split expenses).
 */
is_shadow: boolean, 
/**
 * True if the user account is active and enabled.
 */
is_active: boolean, 
/**
 * The user ID of the creator of this user (for shadow users).
 */
created_by: string | null, 
/**
 * True if Multi-Factor Authentication is enabled.
 */
is_mfa_enabled: boolean, 
/**
 * TOTP MFA shared secret key.
 */
totp_secret: string | null, 
/**
 * MFA recovery/backup codes.
 */
mfa_backup_codes: Array<string> | null, 
/**
 * Timestamp when this user was soft-deleted.
 */
deleted_at: string | null, 
/**
 * The timestamp when the user profile was last updated on the client.
 */
client_updated_at: string, 
/**
 * Version number of the user record.
 */
version: number, 
/**
 * The timestamp when the user was created.
 */
created_at: string, };
