// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Data Transfer Object representing a user alias.
 */
export type UserAliasDto = { 
/**
 * Unique identifier of the user alias.
 */
id: string, 
/**
 * Identifier of the creator real user.
 */
creator_user_id: string, 
/**
 * Optional identifier of the shadow user.
 */
shadow_user_id: string | null, 
/**
 * Optional identifier of the linked user.
 */
linked_user_id: string | null, 
/**
 * The nickname assigned to this alias.
 */
nickname: string, 
/**
 * Creation timestamp.
 */
created_at: string, };
