// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type UserDto = { id: string, email: string | null, username: string, password_hash: string | null, is_shadow: boolean, is_active: boolean, created_by: string | null, is_mfa_enabled: boolean, totp_secret: string | null, mfa_backup_codes: Array<string> | null, deleted_at: string | null, client_updated_at: string, version: number, created_at: string, };
