// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Data Transfer Object representing an active user session.
 */
export type UserSessionDto = { 
/**
 * Unique identifier of the session.
 */
id: string, 
/**
 * Unique identifier of the user who owns this session.
 */
user_id: string, 
/**
 * The User-Agent header from the client's browser/application, if available.
 */
user_agent: string | null, 
/**
 * The IP address from which the session was established, if available.
 */
ip_address: string | null, 
/**
 * The expiration timestamp of the session.
 */
expires_at: string, 
/**
 * The timestamp when the session record was updated on the client.
 */
client_updated_at: string, 
/**
 * Version number of the session record.
 */
version: number, 
/**
 * The timestamp when the session was created.
 */
created_at: string, };
