// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type UserSessionDto = { id: string, user_id: string, user_agent: string | null, ip_address: string | null, expires_at: string, client_updated_at: string, version: number, created_at: string, };
