// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type Item = { id: number, name: string, description: string, item_type: string, };
